name = rainbow_source
title = Rainbow Source
description = Adds coloured water. Fork with buckets and compatibility fixes.
depends = default
optional_depends = bucket_compat, dye
min_minetest_version = 5.4
supported_games = minetest_game
