name = rainbow_source
title = Rainbow Source Redo
description = Fork of Rainbow Source by Shara. Adds coloured water buckets.
depends = default
optional_depends = bucket_compat, dye
min_minetest_version = 5.4
supported_games = minetest_game
